/* =====================================================================
   Bright EngMath — English Entrance Examination
   questions.js  ·  Question bank (5 sets × 30 = 150 unique questions)
   ---------------------------------------------------------------------
   HOW TO EDIT
   -----------
   Each set is an object: { id, title, subtitle, questions: [ ... ] }.

   Each question object uses this schema:
   {
     section : "Grammar" | "Vocabulary" | "Reading" | "Conversation"
               | "Error Identification" | "Cloze"          // used for analysis
     type    : "Sentence Completion"                        // shown as a label
     topic   : "Present Perfect"                            // used for revision tips
     passageId : "s1-read"        // OPTIONAL – groups questions that share a passage
     passage : "….html allowed…"  // OPTIONAL – reading / cloze text (shown above Q)
     instruction : "Choose the best answer."                // OPTIONAL override
     question : "She ___ here since 2019."   // use ___ for a blank
     choices : ["has lived","lived","lives","is living"]
     answer  : 0                  // index (0–3) of the correct choice
     explain : "Thai explanation — why correct, why others wrong, the rule."
     vocab   : [ ["however","อย่างไรก็ตาม"], ["since","ตั้งแต่"] ]  // hint words
   }

   All interface text is English; only `explain` and vocab meanings are Thai.
   ===================================================================== */

const EXAM_SETS = [];

/* =====================================================================
   EXAM SET 1
   ===================================================================== */
EXAM_SETS.push({
  id: 1,
  title: "Examination Set 1",
  subtitle: "Foundation Paper · Grammar, Vocabulary, Reading",
  questions: [
    /* ---- Grammar / Sentence Completion (8) ---- */
    { section:"Grammar", type:"Sentence Completion", topic:"Present Perfect",
      question:"I have already ___ my homework, so I can watch television now.",
      choices:["finished","finish","finishing","to finish"], answer:0,
      explain:"ใช้ <b>Present Perfect</b> (have + V3) เพื่อบอกว่าทำเสร็จแล้วและมีผลถึงปัจจุบัน จึงต้องเป็น <b>finished</b> (V3). ตัว 'finish' เป็นรูปปัจจุบันธรรมดา, 'finishing' ต้องมี be นำหน้า, 'to finish' เป็น infinitive ใช้ไม่ได้กับ have.",
      vocab:[["already","เรียบร้อยแล้ว"],["homework","การบ้าน"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Conditionals (Type 2)",
      question:"If I ___ you, I would apologize to the teacher immediately.",
      choices:["am","was","were","be"], answer:2,
      explain:"ประโยคเงื่อนไขแบบที่ 2 (สมมติไม่จริงในปัจจุบัน) ใช้ <b>were</b> กับทุกประธานในอนุประโยค if (If I were you…). 'was' แม้จะได้ยินในภาษาพูด แต่รูปที่ถูกต้องตามหลักไวยากรณ์คือ were.",
      vocab:[["apologize","ขอโทษ"],["immediately","ทันที"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Reported Speech",
      question:"My sister said that she ___ very tired that evening.",
      choices:["is","was","were","has been"], answer:1,
      explain:"ประโยคเล่าเรื่อง (Reported Speech) ต้องเปลี่ยนกริยาให้เป็นอดีตตามหลัง 'said' ดังนั้น is → <b>was</b>. 'were' ใช้กับประธานพหูพจน์, 'has been' ไม่สอดคล้องกับ said (อดีต).",
      vocab:[["tired","เหนื่อย"],["evening","ตอนเย็น"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Passive Voice",
      question:"The new library ___ last year and is very popular now.",
      choices:["built","was built","is built","has built"], answer:1,
      explain:"เหตุการณ์อดีตที่ประธานถูกกระทำ ใช้ <b>Passive อดีต</b> = was/were + V3 → <b>was built</b>. 'built' เป็น active, 'is built' เป็นปัจจุบัน, 'has built' เป็น active perfect.",
      vocab:[["library","ห้องสมุด"],["popular","เป็นที่นิยม"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Relative Clauses",
      question:"The student ___ won the speech contest is my best friend.",
      choices:["which","who","whom","whose"], answer:1,
      explain:"ใช้ <b>who</b> เป็นประธานของอนุประโยคที่ขยายคน (the student). 'which' ใช้กับสิ่งของ, 'whom' เป็นกรรม, 'whose' แสดงความเป็นเจ้าของ.",
      vocab:[["contest","การแข่งขัน"],["speech","การพูด/สุนทรพจน์"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Gerunds & Infinitives",
      question:"We are all looking forward to ___ our cousins during the holiday.",
      choices:["see","seeing","saw","seen"], answer:1,
      explain:"วลี <b>look forward to</b> ตามด้วยคำนามหรือ V-ing เสมอ (to ในที่นี้เป็นบุพบท) จึงใช้ <b>seeing</b>.",
      vocab:[["look forward to","ตั้งตารอ"],["cousin","ลูกพี่ลูกน้อง"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Prepositions of Time",
      question:"My father has worked at this company ___ 2015.",
      choices:["for","since","from","in"], answer:1,
      explain:"ใช้ <b>since</b> กับ 'จุดเวลาเริ่มต้น' (since 2015) คู่กับ Present Perfect. 'for' ใช้กับช่วงเวลา (for 8 years), 'from' ต้องมี to, 'in' ใช้กับปี/เดือนทั่วไป.",
      vocab:[["company","บริษัท"],["since","ตั้งแต่"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Superlatives",
      question:"This is ___ novel I have ever read.",
      choices:["the more interesting","most interesting","the most interesting","more interesting"], answer:2,
      explain:"โครงสร้าง 'the + est/most' ใช้เปรียบเทียบขั้นสูงสุด และมักตามด้วย 'I have ever…'. คำยาวใช้ <b>the most interesting</b>. ต้องมี 'the' เสมอ.",
      vocab:[["novel","นวนิยาย"],["interesting","น่าสนใจ"]] },

    /* ---- Vocabulary / Synonym / Antonym / Meaning in context (7) ---- */
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to the underlined word: The manager gave a <u>brief</u> report.",
      choices:["short","boring","detailed","loud"], answer:0,
      explain:"'brief' แปลว่า สั้น กระชับ จึงตรงกับ <b>short</b>. 'detailed' (ละเอียด) เป็นคำตรงข้าม, ส่วน boring/loud ความหมายไม่เกี่ยวข้อง.",
      vocab:[["brief","สั้น กระชับ"],["report","รายงาน"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>generous</u>",
      choices:["kind","stingy","wealthy","polite"], answer:1,
      explain:"'generous' แปลว่า ใจกว้าง เอื้อเฟื้อ คำตรงข้ามคือ <b>stingy</b> (ขี้เหนียว). 'kind' และ 'polite' ความหมายใกล้เคียงกัน ไม่ใช่ตรงข้าม.",
      vocab:[["generous","ใจกว้าง"],["stingy","ขี้เหนียว"]] },
    { section:"Vocabulary", type:"Meaning in Context", topic:"Meaning in Context",
      question:"Her explanation was very <u>convincing</u>, so everyone agreed with her plan.",
      choices:["confusing","persuasive","false","tiring"], answer:1,
      explain:"เพราะทุกคนเห็นด้วย แสดงว่าคำอธิบาย 'น่าเชื่อถือ/โน้มน้าวใจได้' = <b>persuasive</b>. 'confusing' (สับสน) และ 'false' (ผิด) ขัดกับการที่ทุกคนเห็นด้วย.",
      vocab:[["convincing","น่าเชื่อถือ"],["persuasive","โน้มน้าวใจ"]] },
    { section:"Vocabulary", type:"Word Choice", topic:"Vocabulary",
      question:"The naughty boy was ___ for breaking the school rules.",
      choices:["rewarded","praised","punished","promoted"], answer:2,
      explain:"การทำผิดกฎย่อมถูก 'ลงโทษ' = <b>punished</b>. 'rewarded/praised/promoted' ล้วนเป็นผลดี ไม่เข้ากับการทำผิด.",
      vocab:[["naughty","ซุกซน"],["punish","ลงโทษ"]] },
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: an <u>enormous</u> stadium",
      choices:["huge","narrow","empty","modern"], answer:0,
      explain:"'enormous' แปลว่า ใหญ่มหึมา ตรงกับ <b>huge</b>. 'narrow' (แคบ) เป็นคนละความหมาย.",
      vocab:[["enormous","ใหญ่มหึมา"],["stadium","สนามกีฬา"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>ancient</u>",
      choices:["historic","modern","famous","ruined"], answer:1,
      explain:"'ancient' แปลว่า โบราณ เก่าแก่ คำตรงข้ามคือ <b>modern</b> (สมัยใหม่). 'historic' ยังหมายถึงเก่า, จึงไม่ใช่ตรงข้าม.",
      vocab:[["ancient","โบราณ"],["modern","สมัยใหม่"]] },
    { section:"Vocabulary", type:"Collocation", topic:"Collocations",
      question:"You must ___ a decision before the deadline this Friday.",
      choices:["do","make","take","have"], answer:1,
      explain:"คำที่ใช้คู่กับ 'decision' คือ <b>make a decision</b> (ตัดสินใจ). ไม่พูดว่า do/take/have a decision.",
      vocab:[["decision","การตัดสินใจ"],["deadline","กำหนดส่ง"]] },

    /* ---- Conversation (4) ---- */
    { section:"Conversation", type:"Conversation", topic:"Polite Requests",
      question:"A: Would you mind opening the window?   B: ___",
      choices:["Yes, I would.","Not at all.","No, thank you.","I'm minding."], answer:1,
      explain:"'Would you mind…?' ตอบตกลงด้วย <b>Not at all.</b> (ไม่รังเกียจเลย = ยินดี). ถ้าตอบ 'Yes, I would.' แปลว่า 'รังเกียจ' คือปฏิเสธ.",
      vocab:[["Would you mind…?","จะรังเกียจไหมถ้า…"],["Not at all.","ไม่เลย/ยินดี"]] },
    { section:"Conversation", type:"Conversation", topic:"Apologies",
      question:"A: I'm really sorry I'm late.   B: ___ We haven't started yet.",
      choices:["Never mind.","You're welcome.","Congratulations.","Not really."], answer:0,
      explain:"ตอบรับคำขอโทษด้วย <b>Never mind.</b> (ไม่เป็นไร). 'You're welcome.' ใช้ตอบขอบคุณ, ส่วนอีกสองตัวไม่เข้าบริบท.",
      vocab:[["Never mind.","ไม่เป็นไร"],["late","สาย"]] },
    { section:"Conversation", type:"Conversation", topic:"Suggestions",
      question:"A: How about visiting the science museum this weekend?   B: ___",
      choices:["You're welcome.","That sounds great!","Here you are.","No, I'm not."], answer:1,
      explain:"'How about…?' เป็นการชวน ตอบรับด้วย <b>That sounds great!</b>. ตัวเลือกอื่นใช้ในสถานการณ์ต่างกัน (ให้ของ/ตอบขอบคุณ).",
      vocab:[["How about…?","…ดีไหม (ชวน)"],["museum","พิพิธภัณฑ์"]] },
    { section:"Conversation", type:"Conversation", topic:"Asking for Information",
      question:"A: ___   B: It's a quarter past seven.",
      choices:["How old are you?","What time is it?","How much is it?","Where are you?"], answer:1,
      explain:"คำตอบบอก 'เวลา' (a quarter past seven) จึงต้องถามด้วย <b>What time is it?</b>.",
      vocab:[["a quarter past","สิบห้านาทีหลัง (โมง)"],["What time…?","กี่โมง"]] },

    /* ---- Error Identification (3) ---- */
    { section:"Error Identification", type:"Error Identification", topic:"Subject–Verb Agreement",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"She <u>don't</u> usually <u>drink</u> coffee <u>in the</u> morning, <u>does she?</u>",
      choices:["don't","drink","in the","does she?"], answer:0,
      explain:"ประธาน 'She' เป็นเอกพจน์บุรุษที่ 3 ต้องใช้ <b>doesn't</b> ไม่ใช่ 'don't'. ส่วน tag question 'does she?' ถูกต้องแล้วเพราะสอดคล้องกับ does.",
      vocab:[["usually","โดยปกติ"],["tag question","ประโยคถามท้าย"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Quantifiers",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"<u>There is</u> <u>many</u> interesting <u>books</u> <u>on</u> the shelf.",
      choices:["There is","many","books","on"], answer:0,
      explain:"ประธานคือ 'books' (พหูพจน์) จึงต้องใช้ <b>There are</b> ไม่ใช่ 'There is'. 'many books' และ 'on the shelf' ถูกต้องแล้ว.",
      vocab:[["shelf","ชั้นวางของ"],["interesting","น่าสนใจ"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Comparatives",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"My brother is <u>more</u> <u>taller</u> <u>than</u> <u>me</u>.",
      choices:["more","taller","than","me"], answer:0,
      explain:"'tall' เป็นคำสั้น เปรียบเทียบขั้นกว่าใช้ 'taller' อยู่แล้ว ไม่ต้องเติม <b>more</b> ซ้ำ (ห้ามใช้ more taller). ที่ถูกคือ 'taller than me'.",
      vocab:[["taller","สูงกว่า"],["than","กว่า"]] },

    /* ---- Cloze Test (4) — one passage ---- */
    { section:"Cloze", type:"Cloze Test", topic:"Vocabulary in Context", passageId:"s1-cloze",
      passage:"<h4>Cloze Passage</h4>Reading is one of the best habits a student can build. It (1)___ the mind and steadily improves vocabulary. Students who read regularly usually (2)___ better in their studies. (3)___, reading for pleasure can reduce stress after a long day. (4)___, everyone should try to read something every single day.",
      question:"Blank (1): It ___ the mind and improves vocabulary.",
      choices:["closes","broadens","breaks","hides"], answer:1,
      explain:"บริบทพูดถึงประโยชน์ของการอ่าน จึงต้องเป็นคำเชิงบวก <b>broadens</b> (เปิดกว้าง/ขยาย) the mind. 'closes/breaks/hides' เป็นความหมายลบ ไม่เข้ากับประโยชน์.",
      vocab:[["broaden","ขยาย/เปิดกว้าง"],["mind","จิตใจ/ความคิด"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Collocations", passageId:"s1-cloze",
      passage:"<h4>Cloze Passage</h4>Reading is one of the best habits a student can build. It (1)___ the mind and steadily improves vocabulary. Students who read regularly usually (2)___ better in their studies. (3)___, reading for pleasure can reduce stress after a long day. (4)___, everyone should try to read something every single day.",
      question:"Blank (2): Students who read regularly usually ___ better in their studies.",
      choices:["make","do","take","play"], answer:1,
      explain:"สำนวน <b>do better</b> = ทำได้ดีขึ้น (do well/badly in studies). ไม่ใช้ make/take/play กับ 'better in studies'.",
      vocab:[["regularly","สม่ำเสมอ"],["do better","ทำได้ดีขึ้น"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors", passageId:"s1-cloze",
      passage:"<h4>Cloze Passage</h4>Reading is one of the best habits a student can build. It (1)___ the mind and steadily improves vocabulary. Students who read regularly usually (2)___ better in their studies. (3)___, reading for pleasure can reduce stress after a long day. (4)___, everyone should try to read something every single day.",
      question:"Blank (3): ___, reading for pleasure can reduce stress.",
      choices:["However","Moreover","Because","Although"], answer:1,
      explain:"ช่องนี้เพิ่มข้อดีอีกข้อ จึงใช้คำเชื่อมแบบ 'เสริม' คือ <b>Moreover</b> (ยิ่งไปกว่านั้น). 'However' ใช้ขัดแย้ง, 'Because/Although' ต้องตามด้วยอนุประโยค.",
      vocab:[["moreover","ยิ่งไปกว่านั้น"],["reduce","ลด"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Modals", passageId:"s1-cloze",
      passage:"<h4>Cloze Passage</h4>Reading is one of the best habits a student can build. It (1)___ the mind and steadily improves vocabulary. Students who read regularly usually (2)___ better in their studies. (3)___, reading for pleasure can reduce stress after a long day. (4)___, everyone should try to read something every single day.",
      question:"Blank (4): ___, everyone should try to read every day.",
      choices:["Therefore","Otherwise","Meanwhile","In contrast"], answer:0,
      explain:"ประโยคนี้เป็น 'ข้อสรุป' จากเหตุผลก่อนหน้า จึงใช้ <b>Therefore</b> (ดังนั้น). 'Otherwise' (มิฉะนั้น) และ 'In contrast' (ตรงกันข้าม) ไม่เข้ากับการสรุป.",
      vocab:[["therefore","ดังนั้น"],["try to","พยายามที่จะ"]] },

    /* ---- Reading Comprehension (4) — one passage ---- */
    { section:"Reading", type:"Reading Comprehension", topic:"Main Idea", passageId:"s1-read",
      passage:"<h4>Reading Passage</h4>The Chao Phraya is the main river of Thailand. It flows through Bangkok and provides water for farming and transportation. Long ago, people built their homes along the river and travelled everywhere by boat. Today, although roads and trains are common, many people still use boats to avoid the heavy traffic. The river is also home to many kinds of fish, and in the evening families often gather on its banks to relax.",
      question:"What is the passage mainly about?",
      choices:["How to catch fish in Bangkok","The importance of the Chao Phraya River","Why trains are better than boats","The history of Thai farming"], answer:1,
      explain:"เนื้อเรื่องกล่าวถึงบทบาทและความสำคัญของแม่น้ำเจ้าพระยาโดยรวม จึงเป็น <b>The importance of the Chao Phraya River</b>. ตัวเลือกอื่นเป็นเพียงรายละเอียดเล็ก ๆ ไม่ใช่ใจความหลัก.",
      vocab:[["provide","จัดหา/ให้"],["transportation","การคมนาคม"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s1-read",
      passage:"<h4>Reading Passage</h4>The Chao Phraya is the main river of Thailand. It flows through Bangkok and provides water for farming and transportation. Long ago, people built their homes along the river and travelled everywhere by boat. Today, although roads and trains are common, many people still use boats to avoid the heavy traffic. The river is also home to many kinds of fish, and in the evening families often gather on its banks to relax.",
      question:"According to the passage, why do some people still travel by boat today?",
      choices:["Because roads are closed","To avoid the heavy traffic","Because boats are free","To catch more fish"], answer:1,
      explain:"ข้อความระบุชัดว่า 'still use boats to avoid the heavy traffic' จึงตอบ <b>To avoid the heavy traffic</b>. ตัวเลือกอื่นไม่ได้กล่าวไว้ในเรื่อง.",
      vocab:[["avoid","หลีกเลี่ยง"],["heavy traffic","การจราจรติดขัด"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Meaning in Context", passageId:"s1-read",
      passage:"<h4>Reading Passage</h4>The Chao Phraya is the main river of Thailand. It flows through Bangkok and provides water for farming and transportation. Long ago, people built their homes along the river and travelled everywhere by boat. Today, although roads and trains are common, many people still use boats to avoid the heavy traffic. The river is also home to many kinds of fish, and in the evening families often gather on its banks to relax.",
      question:"In this passage, the word \"banks\" most nearly means ___.",
      choices:["places to keep money","the sides of the river","large boats","types of fish"], answer:1,
      explain:"คำว่า 'banks' ในบริบทแม่น้ำ หมายถึง <b>ริมฝั่งแม่น้ำ</b> (the sides of the river) ไม่ใช่ธนาคาร เป็นคำหลายความหมาย (homonym) ต้องดูบริบท.",
      vocab:[["bank (river)","ริมฝั่ง"],["gather","มารวมตัว"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Inference", passageId:"s1-read",
      passage:"<h4>Reading Passage</h4>The Chao Phraya is the main river of Thailand. It flows through Bangkok and provides water for farming and transportation. Long ago, people built their homes along the river and travelled everywhere by boat. Today, although roads and trains are common, many people still use boats to avoid the heavy traffic. The river is also home to many kinds of fish, and in the evening families often gather on its banks to relax.",
      question:"Which statement is TRUE according to the passage?",
      choices:["No one uses boats any more.","People long ago travelled by boat.","The river has no fish.","The river flows through Chiang Mai."], answer:1,
      explain:"เรื่องบอกว่า 'Long ago… travelled everywhere by boat' จึงเป็นจริงว่า <b>คนสมัยก่อนเดินทางด้วยเรือ</b>. ตัวเลือกอื่นขัดกับเนื้อเรื่องทั้งหมด.",
      vocab:[["long ago","นานมาแล้ว"],["still","ยังคง"]] }
  ]
});
/* =====================================================================
   EXAM SET 2
   ===================================================================== */
EXAM_SETS.push({
  id: 2,
  title: "Examination Set 2",
  subtitle: "Standard Paper · Tenses, Phrasal Verbs, Environment",
  questions: [
    /* ---- Grammar (8) ---- */
    { section:"Grammar", type:"Sentence Completion", topic:"Past Perfect",
      question:"By the time we reached the cinema, the film ___ already started.",
      choices:["has","had","was","have"], answer:1,
      explain:"เหตุการณ์ที่เกิด 'ก่อน' อีกเหตุการณ์ในอดีต ใช้ <b>Past Perfect</b> = had + V3 → <b>had</b> already started. 'has' เป็นปัจจุบัน, 'was started' จะเป็น passive.",
      vocab:[["by the time","เมื่อถึงตอนที่"],["already","เรียบร้อยแล้ว"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Used to",
      question:"When my grandfather was young, he ___ walk five kilometres to school.",
      choices:["use to","used to","is used to","was used to"], answer:1,
      explain:"เล่านิสัย/เหตุการณ์ในอดีตที่ไม่เกิดแล้ว ใช้ <b>used to</b> + V1. 'is/was used to + V-ing' แปลว่า 'เคยชินกับ' คนละความหมาย.",
      vocab:[["used to","เคย (ในอดีต)"],["kilometre","กิโลเมตร"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"So / Such",
      question:"It was ___ a difficult question that nobody could answer it.",
      choices:["so","such","very","too"], answer:1,
      explain:"โครงสร้าง <b>such + a + adj + noun</b> (such a difficult question). ถ้าใช้ 'so' ต้องตามด้วย adj อย่างเดียว (so difficult).",
      vocab:[["difficult","ยาก"],["nobody","ไม่มีใคร"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Too / Enough",
      question:"This soup is ___ hot to eat right now; let's wait a moment.",
      choices:["enough","so","too","very"], answer:2,
      explain:"โครงสร้าง <b>too + adj + to V</b> = …เกินกว่าที่จะ… (too hot to eat = ร้อนเกินกว่าจะกิน). 'enough' ต้องวางหลัง adj (hot enough).",
      vocab:[["soup","ซุป"],["moment","ครู่หนึ่ง"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Articles",
      question:"My aunt is ___ honest person; she never tells a lie.",
      choices:["a","an","the","(no article)"], answer:1,
      explain:"ใช้ <b>an</b> เพราะ 'honest' ออกเสียงขึ้นต้นด้วยสระ (h ไม่ออกเสียง /ˈɒnɪst/) จึงใช้ an ตามเสียง ไม่ใช่ตามตัวอักษร.",
      vocab:[["honest","ซื่อสัตย์"],["tell a lie","โกหก"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Phrasal Verbs",
      question:"Please ___ your shoes before you enter the temple.",
      choices:["take off","take after","take up","take on"], answer:0,
      explain:"<b>take off</b> = ถอด (เสื้อผ้า/รองเท้า). 'take after' = หน้าตาเหมือน, 'take up' = เริ่มทำงานอดิเรก, 'take on' = รับ (งาน).",
      vocab:[["take off","ถอด"],["temple","วัด"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Tag Questions",
      question:"You have already finished your project, ___",
      choices:["have you?","haven't you?","do you?","didn't you?"], answer:1,
      explain:"ประโยคบอกเล่าที่ใช้ have (perfect) ต้องมี tag เป็นปฏิเสธ <b>haven't you?</b> (บอกเล่า+ ปฏิเสธ). ต้องใช้กริยาช่วยตัวเดียวกัน (have).",
      vocab:[["project","โครงงาน"],["tag question","ประโยคถามท้าย"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"First Conditional",
      question:"If it ___ tomorrow, we will cancel the picnic.",
      choices:["will rain","rains","rained","is raining"], answer:1,
      explain:"เงื่อนไขแบบที่ 1 (อาจเป็นจริงในอนาคต): If + present simple, … will + V1. ในอนุประโยค if ใช้ <b>rains</b> ห้ามใช้ will.",
      vocab:[["cancel","ยกเลิก"],["picnic","ปิกนิก"]] },

    /* ---- Vocabulary (7) ---- */
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>difficult</u> task",
      choices:["easy","tough","short","boring"], answer:1,
      explain:"'difficult' = ยาก ตรงกับ <b>tough</b>. 'easy' เป็นคำตรงข้าม.",
      vocab:[["difficult","ยาก"],["tough","ยาก/หิน"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>increase</u>",
      choices:["rise","grow","decrease","expand"], answer:2,
      explain:"'increase' = เพิ่มขึ้น คำตรงข้ามคือ <b>decrease</b> (ลดลง). rise/grow/expand ล้วนแปลว่าเพิ่มขึ้น.",
      vocab:[["increase","เพิ่มขึ้น"],["decrease","ลดลง"]] },
    { section:"Vocabulary", type:"Meaning in Context", topic:"Meaning in Context",
      question:"The instructions were <u>ambiguous</u>, so the students were not sure what to do.",
      choices:["unclear","simple","exciting","short"], answer:0,
      explain:"เพราะนักเรียนไม่แน่ใจ แสดงว่าคำสั่ง 'กำกวม/ไม่ชัดเจน' = <b>unclear</b>. 'simple/short' ไม่ทำให้สับสน.",
      vocab:[["ambiguous","กำกวม"],["instructions","คำสั่ง/คำแนะนำ"]] },
    { section:"Vocabulary", type:"Phrasal Verb", topic:"Phrasal Verbs",
      question:"The doctor advised my uncle to ___ smoking to protect his health.",
      choices:["give in","give up","give away","give out"], answer:1,
      explain:"<b>give up</b> = เลิก (นิสัย). 'give in' = ยอมแพ้, 'give away' = แจก, 'give out' = แจกจ่าย/หมด.",
      vocab:[["give up","เลิก"],["advise","แนะนำ"]] },
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>courageous</u> firefighter",
      choices:["brave","weak","lazy","clever"], answer:0,
      explain:"'courageous' = กล้าหาญ ตรงกับ <b>brave</b>. 'weak' เป็นตรงข้าม.",
      vocab:[["courageous","กล้าหาญ"],["firefighter","นักดับเพลิง"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>temporary</u>",
      choices:["quick","permanent","cheap","broken"], answer:1,
      explain:"'temporary' = ชั่วคราว คำตรงข้ามคือ <b>permanent</b> (ถาวร).",
      vocab:[["temporary","ชั่วคราว"],["permanent","ถาวร"]] },
    { section:"Vocabulary", type:"Collocation", topic:"Collocations",
      question:"There was ___ rain last night, so the streets are flooded this morning.",
      choices:["strong","heavy","big","hard"], answer:1,
      explain:"ฝนตกหนักใช้คำว่า <b>heavy rain</b> (คำที่ใช้คู่กันตายตัว). ไม่พูดว่า strong/big/hard rain.",
      vocab:[["heavy rain","ฝนตกหนัก"],["flooded","น้ำท่วม"]] },

    /* ---- Conversation (4) ---- */
    { section:"Conversation", type:"Conversation", topic:"Responding to Thanks",
      question:"A: Thank you so much for helping me carry these bags.   B: ___",
      choices:["My pleasure.","Never mind.","Yes, please.","I'm fine, thanks."], answer:0,
      explain:"ตอบรับคำขอบคุณอย่างสุภาพด้วย <b>My pleasure.</b> (ด้วยความยินดี). 'Never mind.' ใช้ตอบคำขอโทษ.",
      vocab:[["My pleasure.","ด้วยความยินดี"],["carry","แบก/ถือ"]] },
    { section:"Conversation", type:"Conversation", topic:"Polite Requests",
      question:"A: Could you pass me the salt, please?   B: ___",
      choices:["Yes, I could.","Certainly, here you are.","No, thank you.","It's my salt."], answer:1,
      explain:"คำขอแบบ 'Could you…?' ตอบรับด้วย <b>Certainly, here you are.</b> (ได้เลย นี่ครับ/ค่ะ). 'Yes, I could.' ฟังดูแปลกและไม่ได้ส่งของให้.",
      vocab:[["pass","ส่งให้"],["Here you are.","นี่ครับ/ค่ะ"]] },
    { section:"Conversation", type:"Conversation", topic:"Declining Politely",
      question:"A: Let's go swimming this afternoon.   B: I'd love to, but ___",
      choices:["I have to study for a test.","that sounds terrible.","you're welcome.","here it is."], answer:0,
      explain:"หลัง 'I'd love to, but…' ต้องตามด้วย 'เหตุผลที่ไปไม่ได้' อย่างสุภาพ = <b>I have to study for a test.</b>.",
      vocab:[["I'd love to","ฉันอยากไปมาก"],["have to","จำเป็นต้อง"]] },
    { section:"Conversation", type:"Conversation", topic:"At a Restaurant",
      question:"Waiter: ___   Customer: I'd like a glass of orange juice, please.",
      choices:["How much is it?","What would you like to drink?","Where is the juice?","How are you today?"], answer:1,
      explain:"ลูกค้าบอกสิ่งที่อยากดื่ม จึงต้องถูกถามว่า <b>What would you like to drink?</b> (รับเครื่องดื่มอะไรดีคะ/ครับ).",
      vocab:[["would like","ต้องการ (สุภาพ)"],["a glass of","หนึ่งแก้ว"]] },

    /* ---- Error Identification (3) ---- */
    { section:"Error Identification", type:"Error Identification", topic:"Irregular Plurals",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"The <u>childrens</u> <u>are</u> <u>playing</u> happily <u>in the</u> park.",
      choices:["childrens","are","playing","in the"], answer:0,
      explain:"'child' มีพหูพจน์ผิดปกติเป็น <b>children</b> อยู่แล้ว ห้ามเติม s ซ้ำเป็น 'childrens'.",
      vocab:[["children","เด็ก ๆ"],["happily","อย่างมีความสุข"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Prepositions (for/since)",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"He <u>has</u> <u>been</u> working here <u>since</u> <u>ten years.</u>",
      choices:["has","been","since","ten years."], answer:2,
      explain:"'ten years' เป็น 'ช่วงเวลา' ต้องใช้ <b>for</b> ไม่ใช่ 'since' (since ใช้กับจุดเริ่มต้น เช่น since 2016).",
      vocab:[["for","เป็นเวลา"],["since","ตั้งแต่"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Subject–Verb Agreement",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"<u>Neither</u> of the two answers <u>are</u> <u>correct</u>, <u>so</u> try again.",
      choices:["Neither","are","correct","so"], answer:1,
      explain:"'Neither of…' ถือเป็นเอกพจน์ ต้องใช้กริยา <b>is</b> ไม่ใช่ 'are' → Neither of the two answers is correct.",
      vocab:[["neither","ไม่ทั้งสอง"],["correct","ถูกต้อง"]] },

    /* ---- Cloze Test (4) ---- */
    { section:"Cloze", type:"Cloze Test", topic:"Passive Voice", passageId:"s2-cloze",
      passage:"<h4>Cloze Passage</h4>Plastic waste is a serious problem for our planet. Every year, millions of tonnes of plastic (1)___ into the ocean, where they harm fish and sea birds. (2)___ plastic is cheap and useful, it does not break down for hundreds of years. To help, people (3)___ reduce the plastic they use. Small habits, (4)___ carrying a cloth bag, can make a big difference.",
      question:"Blank (1): millions of tonnes of plastic ___ into the ocean.",
      choices:["throw","are thrown","threw","throwing"], answer:1,
      explain:"พลาสติก 'ถูกทิ้ง' ลงทะเล เป็นประธานถูกกระทำ จึงใช้ <b>Passive</b> = are thrown. รูป active 'throw/threw' ไม่เข้ากับประธานที่เป็นผู้ถูกกระทำ.",
      vocab:[["waste","ขยะ/ของเสีย"],["are thrown","ถูกทิ้ง"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors", passageId:"s2-cloze",
      passage:"<h4>Cloze Passage</h4>Plastic waste is a serious problem for our planet. Every year, millions of tonnes of plastic (1)___ into the ocean, where they harm fish and sea birds. (2)___ plastic is cheap and useful, it does not break down for hundreds of years. To help, people (3)___ reduce the plastic they use. Small habits, (4)___ carrying a cloth bag, can make a big difference.",
      question:"Blank (2): ___ plastic is cheap and useful, it does not break down for years.",
      choices:["Because","Although","So","Unless"], answer:1,
      explain:"สองประโยคขัดแย้งกัน (ถูก+มีประโยชน์ แต่ย่อยสลายยาก) จึงใช้ <b>Although</b> (แม้ว่า). 'Because' เป็นเหตุผล, 'So' เป็นผลลัพธ์.",
      vocab:[["although","แม้ว่า"],["break down","ย่อยสลาย"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Modals", passageId:"s2-cloze",
      passage:"<h4>Cloze Passage</h4>Plastic waste is a serious problem for our planet. Every year, millions of tonnes of plastic (1)___ into the ocean, where they harm fish and sea birds. (2)___ plastic is cheap and useful, it does not break down for hundreds of years. To help, people (3)___ reduce the plastic they use. Small habits, (4)___ carrying a cloth bag, can make a big difference.",
      question:"Blank (3): people ___ reduce the plastic they use.",
      choices:["should","must not","would","need not"], answer:0,
      explain:"เป็นคำแนะนำที่ควรทำ ใช้ <b>should</b> (ควร). 'must not' = ห้าม, 'need not' = ไม่จำเป็น ซึ่งขัดกับใจความ.",
      vocab:[["should","ควร"],["reduce","ลด"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors (such as)", passageId:"s2-cloze",
      passage:"<h4>Cloze Passage</h4>Plastic waste is a serious problem for our planet. Every year, millions of tonnes of plastic (1)___ into the ocean, where they harm fish and sea birds. (2)___ plastic is cheap and useful, it does not break down for hundreds of years. To help, people (3)___ reduce the plastic they use. Small habits, (4)___ carrying a cloth bag, can make a big difference.",
      question:"Blank (4): Small habits, ___ carrying a cloth bag, can make a difference.",
      choices:["because of","such as","instead of","thanks to"], answer:1,
      explain:"ต้องการยก 'ตัวอย่าง' ของนิสัยเล็ก ๆ จึงใช้ <b>such as</b> (เช่น). ตัวเลือกอื่นเป็นการบอกเหตุผลหรือการแทนที่.",
      vocab:[["such as","เช่น"],["cloth bag","ถุงผ้า"]] },

    /* ---- Reading (4) ---- */
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s2-read",
      passage:"<h4>Reading Passage</h4>Malee is a Grade 6 student who loves science. Every weekend she visits the local library to borrow books about space and animals. Last month, her project on solar energy won first prize at the school science fair. Her teacher says that Malee always asks thoughtful questions and patiently helps her classmates with difficult lessons. Malee dreams of becoming a scientist and one day working for a space agency.",
      question:"What does Malee do every weekend?",
      choices:["She plays sports.","She visits the local library.","She works at a space agency.","She teaches a class."], answer:1,
      explain:"เนื้อเรื่องบอกว่า 'Every weekend she visits the local library' จึงตอบ <b>She visits the local library.</b> ส่วนการทำงานที่ space agency เป็นเพียง 'ความฝัน' ยังไม่เกิดขึ้น.",
      vocab:[["borrow","ยืม"],["weekend","สุดสัปดาห์"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s2-read",
      passage:"<h4>Reading Passage</h4>Malee is a Grade 6 student who loves science. Every weekend she visits the local library to borrow books about space and animals. Last month, her project on solar energy won first prize at the school science fair. Her teacher says that Malee always asks thoughtful questions and patiently helps her classmates with difficult lessons. Malee dreams of becoming a scientist and one day working for a space agency.",
      question:"Why did Malee win first prize last month?",
      choices:["For a poem about animals","For a project on solar energy","For helping the library","For a running race"], answer:1,
      explain:"ข้อความระบุ 'her project on solar energy won first prize' จึงตอบ <b>For a project on solar energy.</b>.",
      vocab:[["solar energy","พลังงานแสงอาทิตย์"],["first prize","รางวัลที่หนึ่ง"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Meaning in Context", passageId:"s2-read",
      passage:"<h4>Reading Passage</h4>Malee is a Grade 6 student who loves science. Every weekend she visits the local library to borrow books about space and animals. Last month, her project on solar energy won first prize at the school science fair. Her teacher says that Malee always asks thoughtful questions and patiently helps her classmates with difficult lessons. Malee dreams of becoming a scientist and one day working for a space agency.",
      question:"The word \"thoughtful\" in the passage is closest in meaning to ___.",
      choices:["careless","well-considered","angry","noisy"], answer:1,
      explain:"'thoughtful questions' = คำถามที่ผ่านการคิดมาอย่างดี ตรงกับ <b>well-considered</b>. 'careless' (สะเพร่า) เป็นตรงข้าม.",
      vocab:[["thoughtful","ที่คิดรอบคอบ"],["well-considered","ผ่านการไตร่ตรอง"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Inference", passageId:"s2-read",
      passage:"<h4>Reading Passage</h4>Malee is a Grade 6 student who loves science. Every weekend she visits the local library to borrow books about space and animals. Last month, her project on solar energy won first prize at the school science fair. Her teacher says that Malee always asks thoughtful questions and patiently helps her classmates with difficult lessons. Malee dreams of becoming a scientist and one day working for a space agency.",
      question:"What can we infer about Malee from the passage?",
      choices:["She dislikes studying.","She is curious and helpful.","She never reads books.","She is often lazy."], answer:1,
      explain:"จากการที่เธอชอบวิทยาศาสตร์ ยืมหนังสือ และช่วยเพื่อน สรุปได้ว่าเธอ <b>ช่างสงสัยและมีน้ำใจ</b> (curious and helpful). ตัวเลือกอื่นขัดกับเนื้อเรื่อง.",
      vocab:[["infer","อนุมาน"],["curious","ช่างสงสัย"]] }
  ]
});
/* =====================================================================
   EXAM SET 3
   ===================================================================== */
EXAM_SETS.push({
  id: 3,
  title: "Examination Set 3",
  subtitle: "Advanced Paper · Modals, Idioms, Wildlife",
  questions: [
    /* ---- Grammar (8) ---- */
    { section:"Grammar", type:"Sentence Completion", topic:"Present Continuous",
      question:"Look! The children ___ happily in the swimming pool.",
      choices:["swim","swims","are swimming","swam"], answer:2,
      explain:"คำว่า 'Look!' บอกเหตุการณ์ที่กำลังเกิด 'ตอนนี้' จึงใช้ <b>Present Continuous</b> = are + V-ing → are swimming.",
      vocab:[["swimming pool","สระว่ายน้ำ"],["happily","อย่างมีความสุข"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Modals of Deduction",
      question:"All the lights are off and the car is gone. They ___ be at home.",
      choices:["must","can't","should","might"], answer:1,
      explain:"หลักฐาน (ไฟดับ รถหาย) บอกว่า 'เป็นไปไม่ได้' ที่จะอยู่บ้าน จึงใช้ <b>can't</b> (can't be = เป็นไปไม่ได้ว่าจะ…). 'must be' แปลว่า 'ต้องอยู่บ้านแน่ ๆ' ซึ่งขัดหลักฐาน.",
      vocab:[["deduction","การสรุปจากหลักฐาน"],["can't be","เป็นไปไม่ได้ว่า"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Wish",
      question:"I wish I ___ taller so that I could reach the top shelf.",
      choices:["am","was","were","be"], answer:2,
      explain:"หลัง 'I wish' เพื่อสมมติสิ่งที่ไม่จริงในปัจจุบัน ใช้ <b>were</b> กับทุกประธาน (I wish I were…).",
      vocab:[["wish","ปรารถนา"],["reach","เอื้อมถึง"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Double Comparatives",
      question:"The more you practise, ___ you become.",
      choices:["better","the better","the best","more good"], answer:1,
      explain:"โครงสร้าง 'The more…, the + comparative…' ใช้แสดงความสัมพันธ์ที่เพิ่มขึ้นคู่กัน จึงเป็น <b>the better</b>.",
      vocab:[["practise","ฝึกฝน"],["become","กลายเป็น"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Quantifiers",
      question:"Hurry up! There isn't ___ time left before the exam.",
      choices:["many","much","few","a few"], answer:1,
      explain:"'time' เป็นนามนับไม่ได้ ใช้ <b>much</b> ในประโยคปฏิเสธ. 'many/few/a few' ใช้กับนามนับได้.",
      vocab:[["hurry up","รีบหน่อย"],["left","เหลืออยู่"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Relative Clauses (whose)",
      question:"That is the girl ___ father is a famous surgeon.",
      choices:["who","which","whose","whom"], answer:2,
      explain:"ต้องการแสดงความเป็นเจ้าของ (พ่อของเธอ) จึงใช้ <b>whose</b> (whose father = พ่อของเธอ). 'who' เป็นประธาน, 'whom' เป็นกรรม.",
      vocab:[["surgeon","ศัลยแพทย์"],["famous","มีชื่อเสียง"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Gerund as Subject",
      question:"___ every morning helps you stay healthy and full of energy.",
      choices:["To exercising","Exercise","Exercising","Exercised"], answer:2,
      explain:"เมื่อใช้กริยาเป็น 'ประธาน' ของประโยค ต้องเป็น Gerund (V-ing) → <b>Exercising</b>. 'To exercising' ผิดรูป, 'Exercise' เดี่ยว ๆ เป็นคำสั่ง.",
      vocab:[["exercise","ออกกำลังกาย"],["energy","พลังงาน"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Reported Questions",
      question:"My teacher asked me where I ___ during the holiday.",
      choices:["go","lived","did go","had gone"], answer:3,
      explain:"คำถามที่ถูกเล่า (reported question) ใช้เรียงประโยคบอกเล่าและเลื่อนกาลเป็นอดีต; เหตุการณ์ก่อนหน้าการถามใช้ <b>had gone</b> (past perfect). โปรดสังเกตว่าไม่มี do/did และไม่กลับประธาน-กริยา.",
      vocab:[["asked","ถาม"],["holiday","วันหยุด"]] },

    /* ---- Vocabulary (7) ---- */
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: an <u>exhausted</u> runner",
      choices:["excited","very tired","hungry","angry"], answer:1,
      explain:"'exhausted' = เหนื่อยล้ามาก ตรงกับ <b>very tired</b>. 'excited' (ตื่นเต้น) คนละความหมาย.",
      vocab:[["exhausted","เหนื่อยล้ามาก"],["runner","นักวิ่ง"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>artificial</u>",
      choices:["natural","fake","plastic","false"], answer:0,
      explain:"'artificial' = ที่ทำขึ้น/เทียม คำตรงข้ามคือ <b>natural</b> (ธรรมชาติ). fake/false มีความหมายใกล้เคียงกับ artificial.",
      vocab:[["artificial","เทียม/ประดิษฐ์"],["natural","ธรรมชาติ"]] },
    { section:"Vocabulary", type:"Meaning in Context", topic:"Meaning in Context",
      question:"The witness gave a <u>reliable</u> account of the accident, so the police believed her.",
      choices:["strange","trustworthy","quick","false"], answer:1,
      explain:"เพราะตำรวจเชื่อ แสดงว่าคำให้การ 'น่าเชื่อถือ/ไว้ใจได้' = <b>trustworthy</b>. 'false' (เท็จ) ขัดกับการที่ตำรวจเชื่อ.",
      vocab:[["reliable","น่าเชื่อถือ"],["witness","พยาน"]] },
    { section:"Vocabulary", type:"Word Choice", topic:"Vocabulary",
      question:"Marie Curie made an important ___ about radioactivity that changed science.",
      choices:["decision","discovery","description","direction"], answer:1,
      explain:"การค้นพบสิ่งใหม่ทางวิทยาศาสตร์ใช้คำว่า <b>discovery</b> (การค้นพบ). อีกสามคำความหมายไม่ตรง.",
      vocab:[["discovery","การค้นพบ"],["radioactivity","กัมมันตภาพรังสี"]] },
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>fragile</u> glass vase",
      choices:["easily broken","very heavy","brightly coloured","quite cheap"], answer:0,
      explain:"'fragile' = เปราะบาง แตกง่าย ตรงกับ <b>easily broken</b>.",
      vocab:[["fragile","เปราะบาง"],["vase","แจกัน"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>victory</u>",
      choices:["success","defeat","prize","winner"], answer:1,
      explain:"'victory' = ชัยชนะ คำตรงข้ามคือ <b>defeat</b> (ความพ่ายแพ้). success/prize/winner ล้วนเกี่ยวกับการชนะ.",
      vocab:[["victory","ชัยชนะ"],["defeat","ความพ่ายแพ้"]] },
    { section:"Vocabulary", type:"Idiom", topic:"Idioms",
      question:"When someone says, \"It's raining cats and dogs,\" they mean it is ___.",
      choices:["raining very heavily","sunny and warm","about to snow","raining lightly"], answer:0,
      explain:"สำนวน <b>rain cats and dogs</b> = ฝนตกหนักมาก (ไม่ได้แปลตามตัวว่าแมวหมาตกลงมา).",
      vocab:[["idiom","สำนวน"],["heavily","อย่างหนัก"]] },

    /* ---- Conversation (4) ---- */
    { section:"Conversation", type:"Conversation", topic:"Small Talk",
      question:"A: How was your trip to Chiang Mai?   B: ___",
      choices:["It was wonderful!","You're welcome.","Here you are.","Not at all."], answer:0,
      explain:"คำถามถึง 'ความรู้สึกต่อทริป' ตอบด้วยการเล่าความรู้สึก <b>It was wonderful!</b>. ตัวเลือกอื่นไม่ตอบคำถาม.",
      vocab:[["trip","การเดินทาง"],["wonderful","วิเศษมาก"]] },
    { section:"Conversation", type:"Conversation", topic:"Asking Permission",
      question:"A: Do you mind if I sit here?   B: ___ Please, make yourself comfortable.",
      choices:["Yes, sit down.","No, go ahead.","Never mind.","It's mine."], answer:1,
      explain:"'Do you mind if…?' ถ้าอนุญาต ตอบ <b>No, go ahead.</b> (ไม่รังเกียจ เชิญเลย). การตอบ 'Yes' จะแปลว่า 'รังเกียจ' = ไม่อนุญาต.",
      vocab:[["Do you mind if…?","จะว่าอะไรไหมถ้า…"],["go ahead","เชิญเลย"]] },
    { section:"Conversation", type:"Conversation", topic:"Giving Advice",
      question:"A: I've had a terrible headache all day.   B: ___",
      choices:["Congratulations!","You should see a doctor.","That's great news.","Help yourself."], answer:1,
      explain:"เมื่อมีคนไม่สบาย ควรให้คำแนะนำ <b>You should see a doctor.</b>. ตัวเลือกอื่นไม่เหมาะกับสถานการณ์.",
      vocab:[["headache","ปวดหัว"],["should","ควร"]] },
    { section:"Conversation", type:"Conversation", topic:"Asking Directions",
      question:"A: ___   B: It's about a ten-minute walk from here.",
      choices:["How far is the station?","How much is the ticket?","What time is it?","Whose bag is this?"], answer:0,
      explain:"คำตอบบอก 'ระยะทาง/เวลาเดิน' จึงต้องถาม <b>How far is the station?</b> (ไกลแค่ไหน).",
      vocab:[["How far…?","ไกลแค่ไหน"],["a ten-minute walk","เดินสิบนาที"]] },

    /* ---- Error Identification (3) ---- */
    { section:"Error Identification", type:"Error Identification", topic:"Adverbs",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"She <u>speaks</u> English <u>more</u> <u>fluent</u> <u>than</u> her brother.",
      choices:["speaks","more","fluent","than"], answer:2,
      explain:"คำที่ขยายกริยา 'speaks' ต้องเป็นกริยาวิเศษณ์ (adverb) → <b>fluently</b> ไม่ใช่ 'fluent' (adjective). ที่ถูก: speaks English more fluently than…",
      vocab:[["fluently","อย่างคล่องแคล่ว"],["than","กว่า"]] },
    { section:"Error Identification", type:"Error Identification", topic:"One of + plural",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"<u>One of</u> my <u>friend</u> <u>is</u> coming to the party <u>tonight.</u>",
      choices:["One of","friend","is","tonight."], answer:1,
      explain:"หลัง 'one of' ต้องเป็นนามพหูพจน์เสมอ → <b>friends</b> (one of my friends). กริยายังเป็นเอกพจน์ 'is' ถูกต้องแล้ว.",
      vocab:[["one of","หนึ่งใน"],["tonight","คืนนี้"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Present Perfect vs Past",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"I <u>have visited</u> that famous museum <u>last</u> <u>week</u> <u>with</u> my class.",
      choices:["have visited","last","week","with"], answer:0,
      explain:"เมื่อมีคำบอกเวลาอดีตชัดเจน 'last week' ต้องใช้ Past Simple → <b>visited</b> ไม่ใช่ Present Perfect 'have visited' (ซึ่งใช้กับเวลาที่ไม่เจาะจง).",
      vocab:[["museum","พิพิธภัณฑ์"],["last week","สัปดาห์ที่แล้ว"]] },

    /* ---- Cloze Test (4) ---- */
    { section:"Cloze", type:"Cloze Test", topic:"Subject–Verb Agreement", passageId:"s3-cloze",
      passage:"<h4>Cloze Passage</h4>Regular exercise is essential for a healthy life. When we play sports or go running, our hearts (1)___ stronger and our minds feel fresh. Doctors recommend that children (2)___ at least one hour of activity every day. (3)___ exercise, a balanced diet also keeps the body strong. Students who stay active often concentrate (4)___ in class and sleep better at night.",
      question:"Blank (1): our hearts ___ stronger.",
      choices:["become","becomes","becoming","became"], answer:0,
      explain:"ประธาน 'our hearts' เป็นพหูพจน์และเป็นความจริงทั่วไป (present) จึงใช้ <b>become</b> (ไม่เติม s). 'became' เป็นอดีต ไม่เข้ากับบริบทข้อเท็จจริง.",
      vocab:[["essential","จำเป็นอย่างยิ่ง"],["become","กลายเป็น"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Subjunctive (recommend that)", passageId:"s3-cloze",
      passage:"<h4>Cloze Passage</h4>Regular exercise is essential for a healthy life. When we play sports or go running, our hearts (1)___ stronger and our minds feel fresh. Doctors recommend that children (2)___ at least one hour of activity every day. (3)___ exercise, a balanced diet also keeps the body strong. Students who stay active often concentrate (4)___ in class and sleep better at night.",
      question:"Blank (2): Doctors recommend that children ___ at least one hour of activity daily.",
      choices:["gets","get","got","getting"], answer:1,
      explain:"หลัง 'recommend that + ประธาน' ใช้กริยารูปฐาน (base form) เสมอ → <b>get</b> (ไม่เติม s แม้ประธานดูเป็นพหูพจน์). นี่คือรูป subjunctive.",
      vocab:[["recommend","แนะนำ"],["activity","กิจกรรม"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors (Besides)", passageId:"s3-cloze",
      passage:"<h4>Cloze Passage</h4>Regular exercise is essential for a healthy life. When we play sports or go running, our hearts (1)___ stronger and our minds feel fresh. Doctors recommend that children (2)___ at least one hour of activity every day. (3)___ exercise, a balanced diet also keeps the body strong. Students who stay active often concentrate (4)___ in class and sleep better at night.",
      question:"Blank (3): ___ exercise, a balanced diet keeps the body strong.",
      choices:["Besides","Despite","Because","Instead"], answer:0,
      explain:"ต้องการเสริมอีกปัจจัยที่ดีต่อสุขภาพ ใช้ <b>Besides</b> (นอกจาก…แล้ว). 'Despite' = แม้ว่า, 'Instead' = แทนที่.",
      vocab:[["besides","นอกจาก"],["balanced diet","อาหารที่สมดุล"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Adverbs / Comparatives", passageId:"s3-cloze",
      passage:"<h4>Cloze Passage</h4>Regular exercise is essential for a healthy life. When we play sports or go running, our hearts (1)___ stronger and our minds feel fresh. Doctors recommend that children (2)___ at least one hour of activity every day. (3)___ exercise, a balanced diet also keeps the body strong. Students who stay active often concentrate (4)___ in class and sleep better at night.",
      question:"Blank (4): active students often concentrate ___ in class.",
      choices:["good","well","better","best"], answer:2,
      explain:"เปรียบเทียบว่า 'ตั้งใจได้ดีกว่า' คู่กับ 'sleep better' จึงใช้ขั้นกว่า <b>better</b> (รูปเปรียบเทียบของ well). 'good' เป็น adjective ใช้ขยายกริยาไม่ได้.",
      vocab:[["concentrate","มีสมาธิ"],["better","ดีกว่า"]] },

    /* ---- Reading (4) ---- */
    { section:"Reading", type:"Reading Comprehension", topic:"Main Idea", passageId:"s3-read",
      passage:"<h4>Reading Passage</h4>The elephant is the largest land animal in the world. Asian elephants, which live in countries such as Thailand and India, are slightly smaller than African elephants. Elephants are highly intelligent and have excellent memories. They live in family groups led by the oldest female, known as the matriarch. Sadly, the number of wild elephants has fallen because their forests are being cut down. Today many people are working hard to protect these gentle giants.",
      question:"What is the main idea of the whole passage?",
      choices:["How to train circus elephants","Key facts about elephants and their protection","The history of Thailand and India","Why forests grow so slowly"], answer:1,
      explain:"เนื้อเรื่องให้ข้อมูลเกี่ยวกับช้างและการอนุรักษ์ จึงเป็น <b>Key facts about elephants and their protection</b>. ตัวเลือกอื่นเป็นรายละเอียดหรือไม่เกี่ยวข้อง.",
      vocab:[["intelligent","ฉลาด"],["protect","ปกป้อง"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s3-read",
      passage:"<h4>Reading Passage</h4>The elephant is the largest land animal in the world. Asian elephants, which live in countries such as Thailand and India, are slightly smaller than African elephants. Elephants are highly intelligent and have excellent memories. They live in family groups led by the oldest female, known as the matriarch. Sadly, the number of wild elephants has fallen because their forests are being cut down. Today many people are working hard to protect these gentle giants.",
      question:"Who leads an elephant family group?",
      choices:["The youngest male","The oldest female","A human trainer","The largest baby"], answer:1,
      explain:"ข้อความบอกว่ากลุ่มนำโดย 'the oldest female… the matriarch' จึงตอบ <b>The oldest female</b>.",
      vocab:[["matriarch","จ่าฝูงตัวเมีย"],["family group","กลุ่มครอบครัว"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s3-read",
      passage:"<h4>Reading Passage</h4>The elephant is the largest land animal in the world. Asian elephants, which live in countries such as Thailand and India, are slightly smaller than African elephants. Elephants are highly intelligent and have excellent memories. They live in family groups led by the oldest female, known as the matriarch. Sadly, the number of wild elephants has fallen because their forests are being cut down. Today many people are working hard to protect these gentle giants.",
      question:"According to the passage, why has the number of wild elephants fallen?",
      choices:["Their forests are being cut down","They are moving to the city","They eat too little food","People give them medicine"], answer:0,
      explain:"เรื่องระบุสาเหตุว่า 'because their forests are being cut down' จึงตอบ <b>Their forests are being cut down</b>.",
      vocab:[["cut down","ตัด (ต้นไม้)"],["wild","ป่า/ตามธรรมชาติ"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Meaning in Context", passageId:"s3-read",
      passage:"<h4>Reading Passage</h4>The elephant is the largest land animal in the world. Asian elephants, which live in countries such as Thailand and India, are slightly smaller than African elephants. Elephants are highly intelligent and have excellent memories. They live in family groups led by the oldest female, known as the matriarch. Sadly, the number of wild elephants has fallen because their forests are being cut down. Today many people are working hard to protect these gentle giants.",
      question:"The word \"gentle\" in \"gentle giants\" is closest in meaning to ___.",
      choices:["fierce","mild","tiny","noisy"], answer:1,
      explain:"'gentle' = อ่อนโยน นุ่มนวล ตรงกับ <b>mild</b>. 'fierce' (ดุร้าย) เป็นตรงข้าม.",
      vocab:[["gentle","อ่อนโยน"],["giant","ยักษ์/สิ่งที่ใหญ่โต"]] }
  ]
});
/* =====================================================================
   EXAM SET 4
   ===================================================================== */
EXAM_SETS.push({
  id: 4,
  title: "Examination Set 4",
  subtitle: "Advanced Paper · Conditionals, Technology, Narrative",
  questions: [
    /* ---- Grammar (8) ---- */
    { section:"Grammar", type:"Sentence Completion", topic:"Future Perfect",
      question:"By next December, my parents ___ this shop for ten years.",
      choices:["will run","will have run","have run","ran"], answer:1,
      explain:"เหตุการณ์ที่จะเสร็จสมบูรณ์ ณ จุดเวลาในอนาคต (By next December) ใช้ <b>Future Perfect</b> = will have + V3 → will have run.",
      vocab:[["run a shop","ดำเนินกิจการร้าน"],["by","ภายใน (เวลา)"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Passive (Present Perfect)",
      question:"All the exam papers ___ already, so you may go home now.",
      choices:["have collected","have been collected","has collected","are collecting"], answer:1,
      explain:"'papers' ถูกเก็บ (ประธานถูกกระทำ) และเน้นว่าเสร็จแล้ว จึงใช้ <b>Passive Present Perfect</b> = have been + V3 → have been collected.",
      vocab:[["collect","เก็บรวบรวม"],["exam paper","กระดาษข้อสอบ"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Third Conditional",
      question:"If she had studied harder, she ___ the entrance exam.",
      choices:["would pass","will pass","would have passed","passed"], answer:2,
      explain:"เงื่อนไขแบบที่ 3 (เหตุการณ์ในอดีตที่ไม่ได้เกิด): If + had + V3, … would have + V3 → <b>would have passed</b>.",
      vocab:[["entrance exam","การสอบเข้า"],["study hard","ตั้งใจเรียน"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Prepositions of Place",
      question:"The frightened cat is hiding ___ the sofa.",
      choices:["under","on","at","into"], answer:0,
      explain:"แมวซ่อนตัว 'ใต้' โซฟา ใช้ <b>under</b>. 'on' = บน, 'into' = เข้าไปข้างใน (มีการเคลื่อนที่).",
      vocab:[["frightened","หวาดกลัว"],["hide","ซ่อน"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Determiners / Agreement",
      question:"___ of the students has to bring a pencil to the test.",
      choices:["All","Both","Each","Many"], answer:2,
      explain:"กริยา 'has' เป็นเอกพจน์ จึงต้องใช้ประธานเอกพจน์ <b>Each</b> (each of… + has). All/Both/Many ต้องใช้ 'have'.",
      vocab:[["each","แต่ละ"],["bring","นำมา"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Infinitive of Purpose",
      question:"My mother went to the market ___ some fresh vegetables.",
      choices:["for buy","to buy","buying","buy"], answer:1,
      explain:"บอกจุดประสงค์ 'เพื่อจะ…' ใช้ <b>to + V1</b> → to buy. ห้ามใช้ 'for + V'.",
      vocab:[["market","ตลาด"],["fresh","สด"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Question Words (Whose)",
      question:"___ umbrella is this? It was left in the classroom.",
      choices:["Who","Who's","Whose","Which"], answer:2,
      explain:"ถามหาเจ้าของสิ่งของใช้ <b>Whose</b> (ของใคร). 'Who's' = who is (คนละความหมาย).",
      vocab:[["umbrella","ร่ม"],["whose","ของใคร"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"So / Neither",
      question:"A: I don't enjoy horror films.   B: ___ do I. They scare me too.",
      choices:["So","Neither","Either","Too"], answer:1,
      explain:"เห็นด้วยกับประโยค 'ปฏิเสธ' ใช้ <b>Neither do I</b> (ฉันก็ไม่เหมือนกัน). 'So do I' ใช้เห็นด้วยกับประโยคบอกเล่า.",
      vocab:[["horror film","หนังสยองขวัญ"],["scare","ทำให้กลัว"]] },

    /* ---- Vocabulary (7) ---- */
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>wealthy</u> businessman",
      choices:["rich","poor","busy","famous"], answer:0,
      explain:"'wealthy' = ร่ำรวย ตรงกับ <b>rich</b>. 'poor' เป็นตรงข้าม.",
      vocab:[["wealthy","ร่ำรวย"],["businessman","นักธุรกิจ"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>success</u>",
      choices:["failure","victory","reward","wealth"], answer:0,
      explain:"'success' = ความสำเร็จ คำตรงข้ามคือ <b>failure</b> (ความล้มเหลว).",
      vocab:[["success","ความสำเร็จ"],["failure","ความล้มเหลว"]] },
    { section:"Vocabulary", type:"Meaning in Context", topic:"Meaning in Context",
      question:"The pilot remained <u>calm</u> during the emergency and landed the plane safely.",
      choices:["relaxed","terrified","furious","exhausted"], answer:0,
      explain:"เพราะลงจอดได้อย่างปลอดภัย แสดงว่านักบิน 'สงบ/ใจเย็น' = <b>relaxed</b>. 'terrified' (หวาดกลัว) ขัดกับการควบคุมสถานการณ์ได้.",
      vocab:[["calm","สงบ/ใจเย็น"],["emergency","เหตุฉุกเฉิน"]] },
    { section:"Vocabulary", type:"Phrasal Verb", topic:"Phrasal Verbs",
      question:"Please ___ the lights when you leave the room to save energy.",
      choices:["turn up","turn off","turn into","turn down"], answer:1,
      explain:"<b>turn off</b> = ปิด (เครื่องใช้ไฟฟ้า). 'turn up' = เพิ่มเสียง, 'turn down' = ลดเสียง/ปฏิเสธ, 'turn into' = กลายเป็น.",
      vocab:[["turn off","ปิด"],["save energy","ประหยัดพลังงาน"]] },
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>valuable</u> diamond ring",
      choices:["worth a lot","very old","brightly coloured","quite small"], answer:0,
      explain:"'valuable' = มีค่ามาก ตรงกับ <b>worth a lot</b> (มีมูลค่าสูง).",
      vocab:[["valuable","มีค่ามาก"],["diamond","เพชร"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>shallow</u> water",
      choices:["deep","wide","clear","cold"], answer:0,
      explain:"'shallow' = ตื้น คำตรงข้ามคือ <b>deep</b> (ลึก).",
      vocab:[["shallow","ตื้น"],["deep","ลึก"]] },
    { section:"Vocabulary", type:"Collocation", topic:"Collocations",
      question:"No matter how hard the test is, she always ___ her best.",
      choices:["makes","does","takes","gives"], answer:1,
      explain:"สำนวน <b>do one's best</b> = ทำเต็มที่. ใช้ 'do' ไม่ใช่ make/take/give.",
      vocab:[["do one's best","ทำให้ดีที่สุด"],["no matter how","ไม่ว่าจะ…เพียงใด"]] },

    /* ---- Conversation (4) ---- */
    { section:"Conversation", type:"Conversation", topic:"Receiving a Gift",
      question:"A: Happy birthday! Here's a little present for you.   B: ___",
      choices:["Oh, thank you so much!","Never mind.","Not at all.","You're welcome."], answer:0,
      explain:"เมื่อได้รับของขวัญ ควรตอบขอบคุณ <b>Oh, thank you so much!</b>. 'You're welcome.' ใช้ตอบเวลาคนอื่นขอบคุณเรา.",
      vocab:[["present","ของขวัญ"],["Thank you so much.","ขอบคุณมาก"]] },
    { section:"Conversation", type:"Conversation", topic:"Showing Sympathy",
      question:"A: I failed my mathematics test today.   B: ___",
      choices:["Congratulations!","Don't worry, you'll do better next time.","That's wonderful news.","Help yourself."], answer:1,
      explain:"เมื่อเพื่อนผิดหวัง ควรปลอบใจ <b>Don't worry, you'll do better next time.</b>. ตัวเลือกอื่นไม่เหมาะกับข่าวร้าย.",
      vocab:[["fail","สอบตก"],["Don't worry.","ไม่ต้องกังวล"]] },
    { section:"Conversation", type:"Conversation", topic:"Offers",
      question:"A: Would you like some more cake?   B: ___ I'm really full.",
      choices:["Yes, give me more.","No, thanks.","Never mind.","Here you are."], answer:1,
      explain:"เมื่ออิ่มแล้วและต้องการปฏิเสธอย่างสุภาพ ใช้ <b>No, thanks.</b> ตามด้วยเหตุผล (I'm full).",
      vocab:[["Would you like…?","รับ…ไหม"],["full","อิ่ม"]] },
    { section:"Conversation", type:"Conversation", topic:"Asking Directions",
      question:"A: ___   B: Sure. Turn left at the traffic lights and it's on your right.",
      choices:["Could you tell me the way to the bank?","How much is the bank?","What is your name?","Whose bank is this?"], answer:0,
      explain:"คำตอบเป็นการบอกทาง จึงต้องถามหาเส้นทาง <b>Could you tell me the way to the bank?</b>.",
      vocab:[["the way to","ทางไป"],["traffic lights","สัญญาณไฟจราจร"]] },

    /* ---- Error Identification (3) ---- */
    { section:"Error Identification", type:"Error Identification", topic:"Agreement (each)",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"<u>Each</u> of the students <u>have</u> <u>their</u> own <u>locker.</u>",
      choices:["Each","have","their","locker."], answer:1,
      explain:"'Each of…' เป็นเอกพจน์ ต้องใช้ <b>has</b> ไม่ใช่ 'have' → Each of the students has…",
      vocab:[["each","แต่ละ"],["locker","ตู้เก็บของ"]] },
    { section:"Error Identification", type:"Error Identification", topic:"-ed / -ing Adjectives",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"I <u>am</u> very <u>interesting</u> <u>in</u> <u>learning</u> Japanese.",
      choices:["am","interesting","in","learning"], answer:1,
      explain:"เมื่อพูดถึง 'ความรู้สึกของคน' ใช้ adjective ลงท้าย -ed → <b>interested</b> (I am interested in…). 'interesting' ใช้บรรยายสิ่งที่ทำให้รู้สึก.",
      vocab:[["interested in","สนใจใน"],["learn","เรียนรู้"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Modal + base verb",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"My little sister <u>can</u> <u>sings</u> <u>very</u> <u>beautifully.</u>",
      choices:["can","sings","very","beautifully."], answer:1,
      explain:"หลังกริยาช่วย (modal) เช่น 'can' ต้องตามด้วยกริยารูปฐาน → <b>sing</b> ไม่ใช่ 'sings'.",
      vocab:[["can","สามารถ"],["beautifully","อย่างไพเราะ"]] },

    /* ---- Cloze Test (4) ---- */
    { section:"Cloze", type:"Cloze Test", topic:"Modal + base verb", passageId:"s4-cloze",
      passage:"<h4>Cloze Passage</h4>The internet has changed the way we live and learn. With a single click, students can (1)___ information from all over the world. However, not everything online is true, so we (2)___ check our sources carefully. Spending too many hours on a screen can be harmful (3)___ it may hurt our eyes and sleep. Used wisely, (4)___, the internet is a powerful tool for learning.",
      question:"Blank (1): students can ___ information from all over the world.",
      choices:["access","accessing","accessed","to access"], answer:0,
      explain:"หลัง 'can' ต้องเป็นกริยารูปฐาน → <b>access</b> (เข้าถึง). รูปอื่นใช้กับ can ไม่ได้.",
      vocab:[["access","เข้าถึง"],["information","ข้อมูล"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Modals", passageId:"s4-cloze",
      passage:"<h4>Cloze Passage</h4>The internet has changed the way we live and learn. With a single click, students can (1)___ information from all over the world. However, not everything online is true, so we (2)___ check our sources carefully. Spending too many hours on a screen can be harmful (3)___ it may hurt our eyes and sleep. Used wisely, (4)___, the internet is a powerful tool for learning.",
      question:"Blank (2): not everything online is true, so we ___ check our sources.",
      choices:["should","need not","must not","would"], answer:0,
      explain:"เป็นคำแนะนำที่ควรทำเพื่อความปลอดภัย ใช้ <b>should</b> (ควร). 'must not' = ห้าม, 'need not' = ไม่จำเป็น ขัดใจความ.",
      vocab:[["source","แหล่งข้อมูล"],["should","ควร"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors (because)", passageId:"s4-cloze",
      passage:"<h4>Cloze Passage</h4>The internet has changed the way we live and learn. With a single click, students can (1)___ information from all over the world. However, not everything online is true, so we (2)___ check our sources carefully. Spending too many hours on a screen can be harmful (3)___ it may hurt our eyes and sleep. Used wisely, (4)___, the internet is a powerful tool for learning.",
      question:"Blank (3): too much screen time can be harmful ___ it may hurt our eyes.",
      choices:["so","because","but","although"], answer:1,
      explain:"ช่องนี้บอก 'เหตุผล' ว่าทำไมจึงเป็นอันตราย ใช้ <b>because</b> (เพราะว่า). 'so' บอกผล, 'but/although' บอกความขัดแย้ง.",
      vocab:[["harmful","เป็นอันตราย"],["screen time","เวลาหน้าจอ"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors (however)", passageId:"s4-cloze",
      passage:"<h4>Cloze Passage</h4>The internet has changed the way we live and learn. With a single click, students can (1)___ information from all over the world. However, not everything online is true, so we (2)___ check our sources carefully. Spending too many hours on a screen can be harmful (3)___ it may hurt our eyes and sleep. Used wisely, (4)___, the internet is a powerful tool for learning.",
      question:"Blank (4): Used wisely, ___, the internet is a powerful tool.",
      choices:["however","therefore","moreover","because"], answer:0,
      explain:"หลังจากพูดถึงข้อเสีย ประโยคนี้กลับมาพูดข้อดี จึงใช้คำแสดงความขัดแย้ง <b>however</b> (อย่างไรก็ตาม).",
      vocab:[["however","อย่างไรก็ตาม"],["wisely","อย่างชาญฉลาด"]] },

    /* ---- Reading (4) ---- */
    { section:"Reading", type:"Reading Comprehension", topic:"Inference (Feelings)", passageId:"s4-read",
      passage:"<h4>Reading Passage</h4>It was the morning of the big competition. Nan had practised the piano every day for months, but now her hands were shaking. As she walked onto the stage, she saw her family smiling in the audience. She took a deep breath and began to play. To her surprise, the music flowed smoothly and the whole room fell silent. When she finished, everyone stood up and clapped loudly. Nan realised that all her hard work had finally paid off.",
      question:"How did Nan feel just before she started to play?",
      choices:["Bored","Nervous","Angry","Sleepy"], answer:1,
      explain:"ข้อความบอกว่า 'her hands were shaking' และ 'took a deep breath' ซึ่งแสดงถึงความ <b>ประหม่า (nervous)</b>.",
      vocab:[["shaking","สั่น"],["nervous","ประหม่า"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s4-read",
      passage:"<h4>Reading Passage</h4>It was the morning of the big competition. Nan had practised the piano every day for months, but now her hands were shaking. As she walked onto the stage, she saw her family smiling in the audience. She took a deep breath and began to play. To her surprise, the music flowed smoothly and the whole room fell silent. When she finished, everyone stood up and clapped loudly. Nan realised that all her hard work had finally paid off.",
      question:"What had Nan done to prepare for the competition?",
      choices:["She had bought a new piano","She had practised every day for months","She had asked her family to play","She had rested for weeks"], answer:1,
      explain:"เรื่องระบุว่า 'had practised the piano every day for months' จึงตอบ <b>She had practised every day for months.</b>.",
      vocab:[["practise","ฝึกซ้อม"],["prepare","เตรียมตัว"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Meaning in Context", passageId:"s4-read",
      passage:"<h4>Reading Passage</h4>It was the morning of the big competition. Nan had practised the piano every day for months, but now her hands were shaking. As she walked onto the stage, she saw her family smiling in the audience. She took a deep breath and began to play. To her surprise, the music flowed smoothly and the whole room fell silent. When she finished, everyone stood up and clapped loudly. Nan realised that all her hard work had finally paid off.",
      question:"The phrase \"paid off\" is closest in meaning to ___.",
      choices:["cost a lot of money","brought good results","was completely wasted","was quickly forgotten"], answer:1,
      explain:"สำนวน <b>pay off</b> = ให้ผลคุ้มค่า/ประสบผลสำเร็จ ตรงกับ <b>brought good results</b> ไม่ได้แปลว่าจ่ายเงิน.",
      vocab:[["pay off","ให้ผลคุ้มค่า"],["result","ผลลัพธ์"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Main Idea / Moral", passageId:"s4-read",
      passage:"<h4>Reading Passage</h4>It was the morning of the big competition. Nan had practised the piano every day for months, but now her hands were shaking. As she walked onto the stage, she saw her family smiling in the audience. She took a deep breath and began to play. To her surprise, the music flowed smoothly and the whole room fell silent. When she finished, everyone stood up and clapped loudly. Nan realised that all her hard work had finally paid off.",
      question:"What is the main lesson of the story?",
      choices:["Never join competitions","Hard work leads to success","Families are always noisy","Playing the piano is easy"], answer:1,
      explain:"เรื่องแสดงให้เห็นว่าการฝึกฝนอย่างหนักนำไปสู่ความสำเร็จ จึงเป็น <b>Hard work leads to success</b>.",
      vocab:[["lesson","บทเรียน"],["hard work","ความพยายาม"]] }
  ]
});
/* =====================================================================
   EXAM SET 5
   ===================================================================== */
EXAM_SETS.push({
  id: 5,
  title: "Examination Set 5",
  subtitle: "Mastery Paper · Mixed Grammar, Idioms, Thai Culture",
  questions: [
    /* ---- Grammar (8) ---- */
    { section:"Grammar", type:"Sentence Completion", topic:"Present Perfect Continuous",
      question:"She ___ for three hours, so she really needs a break now.",
      choices:["has been studying","has studied","is studying","studies"], answer:0,
      explain:"เน้น 'ระยะเวลา' ของการกระทำที่ต่อเนื่องจนถึงปัจจุบัน ใช้ <b>Present Perfect Continuous</b> = has been + V-ing → has been studying.",
      vocab:[["for three hours","เป็นเวลาสามชั่วโมง"],["break","การพัก"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Reported Commands",
      question:"The librarian told the students ___ quiet in the reading room.",
      choices:["be","to be","being","been"], answer:1,
      explain:"คำสั่งที่ถูกเล่า (reported command) ใช้ 'tell someone <b>to</b> + V1' → to be quiet.",
      vocab:[["librarian","บรรณารักษ์"],["quiet","เงียบ"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Passive with Modal",
      question:"This report ___ before the meeting starts tomorrow.",
      choices:["must finish","must be finished","must finishing","must been finished"], answer:1,
      explain:"ประธาน 'report' ถูกกระทำ และมี modal 'must' จึงใช้ <b>must be + V3</b> → must be finished.",
      vocab:[["report","รายงาน"],["meeting","การประชุม"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Conjunctions (unless)",
      question:"You will miss the school bus ___ you leave home right now.",
      choices:["if","unless","because","so"], answer:1,
      explain:"<b>unless</b> = ถ้าไม่ (= if…not). 'You will miss the bus unless you leave now' = ถ้าไม่ออกเดี๋ยวนี้จะพลาดรถ.",
      vocab:[["unless","ถ้าไม่"],["miss the bus","ตกรถ"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Comparatives (as…as)",
      question:"Today's test is not ___ difficult as last week's test.",
      choices:["as","more","too","very"], answer:0,
      explain:"โครงสร้างเปรียบเทียบว่าเท่ากันในรูปปฏิเสธ ใช้ <b>not as + adj + as</b> → not as difficult as. 'more/too/very' ผิดโครงสร้างนี้.",
      vocab:[["as…as","เท่ากับ"],["difficult","ยาก"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Present Simple (Timetable)",
      question:"The express train ___ the station at exactly 6 p.m. every evening.",
      choices:["leave","leaves","is leaving","left"], answer:1,
      explain:"ตารางเวลาที่เกิดซ้ำเป็นประจำใช้ Present Simple; ประธาน 'train' เอกพจน์ จึงเติม s → <b>leaves</b>.",
      vocab:[["express train","รถไฟด่วน"],["leave","ออกจาก"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Articles (the)",
      question:"Mount Everest is ___ highest mountain in the world.",
      choices:["a","an","the","(no article)"], answer:2,
      explain:"ใช้ <b>the</b> กับคำขั้นสูงสุด (the highest) และสิ่งที่มีเพียงหนึ่งเดียวในโลก.",
      vocab:[["highest","สูงที่สุด"],["mountain","ภูเขา"]] },
    { section:"Grammar", type:"Sentence Completion", topic:"Gerunds (enjoy + ing)",
      question:"My younger brother enjoys ___ comic books on lazy Sunday afternoons.",
      choices:["read","to read","reading","reads"], answer:2,
      explain:"กริยา <b>enjoy</b> ต้องตามด้วย V-ing เสมอ → enjoys reading. ไม่ใช้ to + V หลัง enjoy.",
      vocab:[["enjoy","สนุกกับ/ชอบ"],["comic book","หนังสือการ์ตูน"]] },

    /* ---- Vocabulary (7) ---- */
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>rapid</u> increase in prices",
      choices:["quick","slow","small","steady"], answer:0,
      explain:"'rapid' = รวดเร็ว ตรงกับ <b>quick</b>. 'slow' เป็นตรงข้าม.",
      vocab:[["rapid","รวดเร็ว"],["increase","การเพิ่มขึ้น"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>polite</u>",
      choices:["rude","kind","gentle","calm"], answer:0,
      explain:"'polite' = สุภาพ คำตรงข้ามคือ <b>rude</b> (หยาบคาย). kind/gentle มีความหมายใกล้เคียงกับ polite.",
      vocab:[["polite","สุภาพ"],["rude","หยาบคาย"]] },
    { section:"Vocabulary", type:"Meaning in Context", topic:"Meaning in Context",
      question:"The road was <u>slippery</u> after the rain, so the drivers had to slow down.",
      choices:["dry and safe","smooth and dangerous to drive on","very wide","brand new"], answer:1,
      explain:"เพราะคนขับต้องชะลอความเร็ว แสดงว่าถนน 'ลื่นและอันตราย' = <b>smooth and dangerous to drive on</b>. 'dry and safe' ขัดกับการต้องระวัง.",
      vocab:[["slippery","ลื่น"],["slow down","ชะลอความเร็ว"]] },
    { section:"Vocabulary", type:"Word Choice", topic:"Vocabulary",
      question:"The firefighters were praised for their ___ during the dangerous rescue.",
      choices:["laziness","bravery","weakness","fear"], answer:1,
      explain:"การได้รับคำชมจากการช่วยเหลือที่อันตราย มาจาก 'ความกล้าหาญ' = <b>bravery</b>. 'fear/weakness/laziness' เป็นด้านลบ ไม่ได้รับคำชม.",
      vocab:[["bravery","ความกล้าหาญ"],["rescue","การช่วยเหลือ"]] },
    { section:"Vocabulary", type:"Synonym", topic:"Synonyms",
      question:"Choose the word closest in meaning to: a <u>strange</u> noise in the attic",
      choices:["odd","normal","quiet","pleasant"], answer:0,
      explain:"'strange' = แปลกประหลาด ตรงกับ <b>odd</b>. 'normal' เป็นตรงข้าม.",
      vocab:[["strange","แปลก"],["attic","ห้องใต้หลังคา"]] },
    { section:"Vocabulary", type:"Antonym", topic:"Antonyms",
      question:"Choose the word OPPOSITE in meaning to: <u>expand</u>",
      choices:["shrink","grow","stretch","widen"], answer:0,
      explain:"'expand' = ขยายตัว คำตรงข้ามคือ <b>shrink</b> (หดตัว). grow/stretch/widen ล้วนหมายถึงขยาย.",
      vocab:[["expand","ขยาย"],["shrink","หดตัว"]] },
    { section:"Vocabulary", type:"Idiom", topic:"Idioms",
      question:"Before the show, the director said, \"Break a leg!\" This means ___.",
      choices:["Be careful not to fall","Good luck","Run away quickly","Go home now"], answer:1,
      explain:"สำนวน <b>Break a leg!</b> = ขอให้โชคดี (ใช้อวยพรก่อนการแสดง) ไม่ได้แปลตามตัวว่าให้ขาหัก.",
      vocab:[["Break a leg!","ขอให้โชคดี"],["director","ผู้กำกับ"]] },

    /* ---- Conversation (4) ---- */
    { section:"Conversation", type:"Conversation", topic:"Borrowing",
      question:"A: Could I borrow your pen for a moment?   B: ___",
      choices:["Of course, here you are.","Yes, I could.","No, it's a pen.","Never mind."], answer:0,
      explain:"คำขอยืมแบบสุภาพ ตอบรับด้วย <b>Of course, here you are.</b> พร้อมส่งของให้. 'Yes, I could.' ฟังดูไม่เป็นธรรมชาติ.",
      vocab:[["borrow","ยืม"],["for a moment","สักครู่"]] },
    { section:"Conversation", type:"Conversation", topic:"Talking about Jobs",
      question:"A: What does your father do?   B: ___",
      choices:["He's an engineer.","He is fine, thank you.","He's doing his homework.","He does it very well."], answer:0,
      explain:"คำถาม 'What does he do?' ถามถึง 'อาชีพ' จึงตอบด้วยอาชีพ <b>He's an engineer.</b> ไม่ใช่กิจกรรมที่กำลังทำ.",
      vocab:[["What do you do?","คุณทำงานอะไร"],["engineer","วิศวกร"]] },
    { section:"Conversation", type:"Conversation", topic:"Good Wishes",
      question:"A: I'm flying to Japan for a holiday next week.   B: ___",
      choices:["Have a great trip!","Never mind.","You're welcome.","Not really."], answer:0,
      explain:"เมื่อเพื่อนจะไปเที่ยว ควรอวยพร <b>Have a great trip!</b> (ขอให้เที่ยวสนุก).",
      vocab:[["Have a great trip!","ขอให้เที่ยวสนุก"],["holiday","วันหยุด"]] },
    { section:"Conversation", type:"Conversation", topic:"Shopping",
      question:"A: ___   B: They cost fifty baht each.",
      choices:["How much are they?","How many are there?","Where are they?","Whose are they?"], answer:0,
      explain:"คำตอบบอก 'ราคา' (fifty baht each) จึงต้องถาม <b>How much are they?</b>.",
      vocab:[["How much…?","ราคาเท่าไร"],["each","ต่ออัน"]] },

    /* ---- Error Identification (3) ---- */
    { section:"Error Identification", type:"Error Identification", topic:"Fewer vs Less",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"There <u>are</u> <u>less</u> <u>students</u> in class today <u>than</u> yesterday.",
      choices:["are","less","students","than"], answer:1,
      explain:"'students' เป็นนามนับได้พหูพจน์ ต้องใช้ <b>fewer</b> ไม่ใช่ 'less' (less ใช้กับนามนับไม่ได้ เช่น less water).",
      vocab:[["fewer","น้อยกว่า (นับได้)"],["less","น้อยกว่า (นับไม่ได้)"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Irregular Verbs",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"He <u>runned</u> <u>quickly</u> <u>to</u> <u>catch</u> the bus this morning.",
      choices:["runned","quickly","to","catch"], answer:0,
      explain:"'run' เป็นกริยาอปกติ รูปอดีตคือ <b>ran</b> ไม่ใช่ 'runned'.",
      vocab:[["ran","วิ่ง (อดีต)"],["catch the bus","ขึ้นรถเมล์ให้ทัน"]] },
    { section:"Error Identification", type:"Error Identification", topic:"Causative (make + base)",
      instruction:"Choose the underlined part that is INCORRECT.",
      question:"My mother <u>makes</u> me <u>to clean</u> my <u>room</u> every <u>weekend.</u>",
      choices:["makes","to clean","room","weekend."], answer:1,
      explain:"โครงสร้าง 'make someone + V1' ไม่มี to → <b>clean</b> ไม่ใช่ 'to clean' (My mother makes me clean…).",
      vocab:[["make someone do","บังคับ/ทำให้ทำ"],["clean","ทำความสะอาด"]] },

    /* ---- Cloze Test (4) ---- */
    { section:"Cloze", type:"Cloze Test", topic:"Vocabulary in Context", passageId:"s5-cloze",
      passage:"<h4>Cloze Passage</h4>Recycling is a simple way to protect our environment. Instead of throwing paper and bottles away, we can (1)___ them so that new products can be made. Many schools now have special bins (2)___ students can sort their waste easily. (3)___ everyone recycles just a little, the total effect on the planet is enormous. Teachers say that good habits, (4)___ recycling, should begin at a young age.",
      question:"Blank (1): instead of throwing them away, we can ___ them.",
      choices:["waste","recycle","pollute","burn"], answer:1,
      explain:"บริบทพูดถึงการนำกลับมาใช้ใหม่เพื่อผลิตสินค้าใหม่ จึงใช้ <b>recycle</b> (รีไซเคิล). waste/pollute/burn ขัดกับการรักษาสิ่งแวดล้อม.",
      vocab:[["recycle","นำกลับมาใช้ใหม่"],["instead of","แทนที่จะ"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Relative Adverbs (where)", passageId:"s5-cloze",
      passage:"<h4>Cloze Passage</h4>Recycling is a simple way to protect our environment. Instead of throwing paper and bottles away, we can (1)___ them so that new products can be made. Many schools now have special bins (2)___ students can sort their waste easily. (3)___ everyone recycles just a little, the total effect on the planet is enormous. Teachers say that good habits, (4)___ recycling, should begin at a young age.",
      question:"Blank (2): schools have special bins ___ students can sort their waste.",
      choices:["which","where","who","what"], answer:1,
      explain:"ขยายสถานที่ (bins ที่ใช้แยกขยะ) ใช้ relative adverb <b>where</b>. 'which' จะต้องตามด้วยประโยคที่ bins เป็นประธาน/กรรม.",
      vocab:[["sort","คัดแยก"],["bin","ถังขยะ"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Conjunctions (If)", passageId:"s5-cloze",
      passage:"<h4>Cloze Passage</h4>Recycling is a simple way to protect our environment. Instead of throwing paper and bottles away, we can (1)___ them so that new products can be made. Many schools now have special bins (2)___ students can sort their waste easily. (3)___ everyone recycles just a little, the total effect on the planet is enormous. Teachers say that good habits, (4)___ recycling, should begin at a young age.",
      question:"Blank (3): ___ everyone recycles just a little, the total effect is enormous.",
      choices:["Although","If","Unless","But"], answer:1,
      explain:"เป็นเงื่อนไข 'ถ้าทุกคนช่วยกันเล็กน้อย' ใช้ <b>If</b>. 'Unless' = ถ้าไม่ ซึ่งกลับความหมาย.",
      vocab:[["if","ถ้า"],["enormous","มหาศาล"]] },
    { section:"Cloze", type:"Cloze Test", topic:"Connectors (such as)", passageId:"s5-cloze",
      passage:"<h4>Cloze Passage</h4>Recycling is a simple way to protect our environment. Instead of throwing paper and bottles away, we can (1)___ them so that new products can be made. Many schools now have special bins (2)___ students can sort their waste easily. (3)___ everyone recycles just a little, the total effect on the planet is enormous. Teachers say that good habits, (4)___ recycling, should begin at a young age.",
      question:"Blank (4): good habits, ___ recycling, should begin at a young age.",
      choices:["such as","because of","instead of","in spite of"], answer:0,
      explain:"ยกตัวอย่างของ 'นิสัยที่ดี' จึงใช้ <b>such as</b> (เช่น).",
      vocab:[["such as","เช่น"],["habit","นิสัย"]] },

    /* ---- Reading (4) ---- */
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s5-read",
      passage:"<h4>Reading Passage</h4>Loy Krathong is one of Thailand's most beautiful festivals. It takes place on the night of the full moon in the twelfth lunar month, usually in November. On this night, people make small floats, called krathong, from banana leaves and decorate them with flowers, candles, and incense. They float their krathong on rivers and canals to show respect to the water and to let go of bad luck. The soft light of thousands of candles on the water is a truly magical sight.",
      question:"When does Loy Krathong take place?",
      choices:["On the full-moon night of the twelfth lunar month","On New Year's Day","During the hot season in April","Every Sunday in December"], answer:0,
      explain:"ข้อความระบุ 'on the night of the full moon in the twelfth lunar month' จึงตอบ <b>On the full-moon night of the twelfth lunar month</b>.",
      vocab:[["full moon","พระจันทร์เต็มดวง"],["lunar month","เดือนตามจันทรคติ"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail", passageId:"s5-read",
      passage:"<h4>Reading Passage</h4>Loy Krathong is one of Thailand's most beautiful festivals. It takes place on the night of the full moon in the twelfth lunar month, usually in November. On this night, people make small floats, called krathong, from banana leaves and decorate them with flowers, candles, and incense. They float their krathong on rivers and canals to show respect to the water and to let go of bad luck. The soft light of thousands of candles on the water is a truly magical sight.",
      question:"What are krathong mainly made from?",
      choices:["Plastic bottles","Banana leaves","Coloured paper","Clay and stone"], answer:1,
      explain:"เรื่องบอกว่า 'make small floats… from banana leaves' จึงตอบ <b>Banana leaves</b>.",
      vocab:[["float","สิ่งที่ลอยน้ำ/ลอย"],["banana leaf","ใบตอง"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Detail / Purpose", passageId:"s5-read",
      passage:"<h4>Reading Passage</h4>Loy Krathong is one of Thailand's most beautiful festivals. It takes place on the night of the full moon in the twelfth lunar month, usually in November. On this night, people make small floats, called krathong, from banana leaves and decorate them with flowers, candles, and incense. They float their krathong on rivers and canals to show respect to the water and to let go of bad luck. The soft light of thousands of candles on the water is a truly magical sight.",
      question:"Why do people float their krathong?",
      choices:["To catch fish for dinner","To show respect to the water and let go of bad luck","To win a competition","To clean the river"], answer:1,
      explain:"ข้อความระบุจุดประสงค์ 'to show respect to the water and to let go of bad luck' จึงตอบข้อนี้.",
      vocab:[["show respect","แสดงความเคารพ"],["let go of","ปล่อยวาง"]] },
    { section:"Reading", type:"Reading Comprehension", topic:"Meaning in Context", passageId:"s5-read",
      passage:"<h4>Reading Passage</h4>Loy Krathong is one of Thailand's most beautiful festivals. It takes place on the night of the full moon in the twelfth lunar month, usually in November. On this night, people make small floats, called krathong, from banana leaves and decorate them with flowers, candles, and incense. They float their krathong on rivers and canals to show respect to the water and to let go of bad luck. The soft light of thousands of candles on the water is a truly magical sight.",
      question:"In this passage, the word \"magical\" is closest in meaning to ___.",
      choices:["ordinary","wonderful","frightening","boring"], answer:1,
      explain:"'magical' ในที่นี้ = งดงามน่าอัศจรรย์ ตรงกับ <b>wonderful</b>. 'ordinary' (ธรรมดา) เป็นตรงข้าม.",
      vocab:[["magical","น่าอัศจรรย์"],["sight","ภาพ/ทิวทัศน์"]] }
  ]
});

/* ---------------------------------------------------------------------
   Expose the data for script.js (and allow module import if needed).
   ------------------------------------------------------------------- */
if (typeof window !== "undefined") { window.EXAM_SETS = EXAM_SETS; }
if (typeof module !== "undefined" && module.exports) { module.exports = { EXAM_SETS }; }
